package com.careerpilot.application.resume;

import com.careerpilot.domain.job.Job;
import com.careerpilot.domain.job.JobMatch;
import com.careerpilot.domain.job.JobRepository;
import com.careerpilot.domain.resume.ParseStatus;
import com.careerpilot.domain.resume.Resume;
import com.careerpilot.domain.resume.ResumeRepository;
import com.careerpilot.infrastructure.ai.OpenAIClient;
import com.careerpilot.infrastructure.document.AtsDocumentRenderer;
import com.careerpilot.infrastructure.document.AtsRenderedDocument;
import com.careerpilot.infrastructure.document.ResumeJson;
import com.careerpilot.infrastructure.storage.R2StorageClient;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

/**
 * Unit tests updated after the @Async self-invocation fix (F6-12).
 *
 * Architecture post-fix:
 *   ResumeTailoringService  → orchestrates validation + PENDING creation
 *   ResumeTailoringWorker   → owns @Async processAsync (the actual pipeline)
 *
 * Tests for the synchronous entry-point (inititateTailoring) remain on
 * ResumeTailoringService.  Tests for the async pipeline target
 * ResumeTailoringWorker directly using its real dependencies (no Spring context).
 */
@ExtendWith(MockitoExtension.class)
class ResumeTailoringServiceTest {

    // ── Shared mocks ──────────────────────────────────────────────────────────

    @Mock private ResumeRepository resumeRepository;
    @Mock private JobRepository    jobRepository;
    @Mock private OpenAIClient      openAIClient;
    @Mock private AtsDocumentRenderer documentRenderer;
    @Mock private R2StorageClient   r2StorageClient;
    @Mock private com.careerpilot.application.job.JobMatchingService jobMatchingService;

    private final ObjectMapper objectMapper = new ObjectMapper();

    // ── System under test ─────────────────────────────────────────────────────

    private ResumeTailoringWorker  resumeTailoringWorker;
    private ResumeTailoringService resumeTailoringService;

    @BeforeEach
    void setUp() {
        // Worker owns the pipeline; Service owns the orchestration.
        resumeTailoringWorker = new ResumeTailoringWorker(
                resumeRepository, openAIClient, documentRenderer, r2StorageClient, objectMapper);

        // ResumeTailoringWorker mock used by the service so we can verify delegation
        ResumeTailoringWorker workerSpy = spy(resumeTailoringWorker);

        resumeTailoringService = new ResumeTailoringService(
                resumeRepository, jobRepository, workerSpy, jobMatchingService);
    }

    // ── inititateTailoring tests (unchanged business logic) ───────────────────

    @Test
    void testInititateTailoring_Success() {
        UUID userId        = UUID.randomUUID();
        UUID jobId         = UUID.randomUUID();
        UUID sourceResumeId = UUID.randomUUID();

        Resume source = new Resume();
        source.setId(sourceResumeId);
        source.setUserId(userId);
        source.setParseStatus(ParseStatus.DONE);
        source.setSourceType("UPLOADED");

        Job job = new Job();
        job.setId(jobId);

        when(resumeRepository.findById(sourceResumeId)).thenReturn(Optional.of(source));
        when(jobRepository.findById(jobId)).thenReturn(Optional.of(job));
        when(jobRepository.findMatchByUserIdAndJobId(userId, jobId)).thenReturn(Optional.of(new JobMatch()));
        when(resumeRepository.findGeneratedByUserIdAndJobId(userId, jobId)).thenReturn(Optional.empty());

        UUID generatedId = resumeTailoringService.inititateTailoring(userId, jobId, sourceResumeId);

        // In a pure unit test without a real DB, the ID generated by the DB might be null.
        // We just need to verify that save() was called.
        verify(resumeRepository).save(any(Resume.class));
    }

    @Test
    void testInititateTailoring_ReturnExisting() {
        UUID userId        = UUID.randomUUID();
        UUID jobId         = UUID.randomUUID();
        UUID sourceResumeId = UUID.randomUUID();

        Resume source = new Resume();
        source.setId(sourceResumeId);
        source.setUserId(userId);
        source.setParseStatus(ParseStatus.DONE);
        source.setSourceType("UPLOADED");

        Resume existing = new Resume();
        existing.setId(UUID.randomUUID());
        existing.setParseStatus(ParseStatus.DONE);

        when(resumeRepository.findById(sourceResumeId)).thenReturn(Optional.of(source));
        when(jobRepository.findById(jobId)).thenReturn(Optional.of(new Job()));
        when(jobRepository.findMatchByUserIdAndJobId(userId, jobId)).thenReturn(Optional.of(new JobMatch()));
        when(resumeRepository.findGeneratedByUserIdAndJobId(userId, jobId)).thenReturn(Optional.of(existing));

        UUID generatedId = resumeTailoringService.inititateTailoring(userId, jobId, sourceResumeId);

        assertEquals(existing.getId(), generatedId);
    }

    @Test
    void testInititateTailoring_SourceNotFound() {
        UUID userId = UUID.randomUUID();
        UUID jobId  = UUID.randomUUID();
        UUID sourceId = UUID.randomUUID();
        when(resumeRepository.findById(sourceId)).thenReturn(Optional.empty());

        assertThrows(IllegalArgumentException.class,
                () -> resumeTailoringService.inititateTailoring(userId, jobId, sourceId));
    }

    @Test
    void testInititateTailoring_WrongUser() {
        UUID userId   = UUID.randomUUID();
        UUID jobId    = UUID.randomUUID();
        UUID sourceId = UUID.randomUUID();

        Resume source = new Resume();
        source.setUserId(UUID.randomUUID()); // different user
        when(resumeRepository.findById(sourceId)).thenReturn(Optional.of(source));

        assertThrows(SecurityException.class,
                () -> resumeTailoringService.inititateTailoring(userId, jobId, sourceId));
    }

    @Test
    void testInititateTailoring_NotDone() {
        UUID userId   = UUID.randomUUID();
        UUID jobId    = UUID.randomUUID();
        UUID sourceId = UUID.randomUUID();

        Resume source = new Resume();
        source.setUserId(userId);
        source.setParseStatus(ParseStatus.PENDING);
        when(resumeRepository.findById(sourceId)).thenReturn(Optional.of(source));

        assertThrows(IllegalArgumentException.class,
                () -> resumeTailoringService.inititateTailoring(userId, jobId, sourceId));
    }

    @Test
    void testInititateTailoring_IsGenerated() {
        UUID userId   = UUID.randomUUID();
        UUID jobId    = UUID.randomUUID();
        UUID sourceId = UUID.randomUUID();

        Resume source = new Resume();
        source.setUserId(userId);
        source.setParseStatus(ParseStatus.DONE);
        source.setSourceType("GENERATED");
        when(resumeRepository.findById(sourceId)).thenReturn(Optional.of(source));

        assertThrows(IllegalArgumentException.class,
                () -> resumeTailoringService.inititateTailoring(userId, jobId, sourceId));
    }

    @Test
    void testInititateTailoring_JobNotFound() {
        UUID userId   = UUID.randomUUID();
        UUID jobId    = UUID.randomUUID();
        UUID sourceId = UUID.randomUUID();

        Resume source = new Resume();
        source.setUserId(userId);
        source.setParseStatus(ParseStatus.DONE);
        source.setSourceType("UPLOADED");
        when(resumeRepository.findById(sourceId)).thenReturn(Optional.of(source));
        when(jobRepository.findById(jobId)).thenReturn(Optional.empty());

        assertThrows(IllegalArgumentException.class,
                () -> resumeTailoringService.inititateTailoring(userId, jobId, sourceId));
    }

    @Test
    void testInititateTailoring_JobMatchNotFound_TriggersScoring() {
        UUID userId   = UUID.randomUUID();
        UUID jobId    = UUID.randomUUID();
        UUID sourceId = UUID.randomUUID();

        Resume source = new Resume();
        source.setUserId(userId);
        source.setParseStatus(ParseStatus.DONE);
        source.setSourceType("UPLOADED");
        when(resumeRepository.findById(sourceId)).thenReturn(Optional.of(source));
        when(jobRepository.findById(jobId)).thenReturn(Optional.of(new Job()));
        when(jobRepository.findMatchByUserIdAndJobId(userId, jobId)).thenReturn(Optional.empty());

        resumeTailoringService.inititateTailoring(userId, jobId, sourceId);

        verify(jobMatchingService).matchJob(userId, jobId);
        verify(resumeRepository).save(any(Resume.class));
    }

    // ── processAsync tests — now target ResumeTailoringWorker ────────────────

    @Test
    void testProcessAsync_Success() throws Exception {
        UUID resumeId = UUID.randomUUID();
        UUID userId   = UUID.randomUUID();

        Resume source = new Resume();
        source.setParsedSkills("{\"skills\":[\"Java\"]}");
        source.setParsedExperience("[{\"company\":\"Test Co\"}]");

        Job job = new Job();
        job.setTitle("Dev");
        job.setDescription("Do stuff");
        job.setRequiredSkills(List.of("Java"));

        JobMatch match = new JobMatch();
        match.setMatchingSkills(List.of("Java"));
        match.setMissingSkills(List.of("Spring"));

        Resume pending = new Resume();
        pending.setId(resumeId);
        pending.setParseStatus(ParseStatus.PENDING);

        when(resumeRepository.findById(resumeId)).thenReturn(Optional.of(pending));
        when(openAIClient.tailorResume(anyList(), anyString(), anyString(), anyString(), anyList(), anyList(), anyList()))
                .thenReturn("{\"experience\":[{\"company\":\"Test Co\"}],\"unmatchedKeywords\":[]}");

        AtsRenderedDocument doc = new AtsRenderedDocument("pdf".getBytes(), "docx".getBytes());
        when(documentRenderer.render(any(ResumeJson.class), anyString())).thenReturn(doc);

        when(r2StorageClient.uploadGeneratedJson(any(), any(), any())).thenReturn("jsonKey");
        when(r2StorageClient.uploadGeneratedPdf(any(), any(), any())).thenReturn("pdfKey");
        when(r2StorageClient.uploadGeneratedDocx(any(), any(), any())).thenReturn("docxKey");

        resumeTailoringWorker.processAsync(resumeId, userId, source, job, match);

        verify(resumeRepository, times(2)).save(pending);
        assertEquals(ParseStatus.DONE, pending.getParseStatus());
        assertEquals("jsonKey", pending.getFileKey());
    }

    @Test
    void testProcessAsync_Failure() {
        UUID resumeId = UUID.randomUUID();
        UUID userId   = UUID.randomUUID();

        Resume source = new Resume();
        Job job = new Job();
        JobMatch match = new JobMatch();

        Resume pending = new Resume();
        pending.setId(resumeId);
        pending.setParseStatus(ParseStatus.PENDING);

        when(resumeRepository.findById(resumeId)).thenReturn(Optional.of(pending));
        when(openAIClient.tailorResume(anyList(), anyString(), anyString(), anyString(), anyList(), anyList(), anyList()))
                .thenThrow(new RuntimeException("API Error"));

        resumeTailoringWorker.processAsync(resumeId, userId, source, job, match);

        verify(resumeRepository, times(2)).save(pending);
        assertEquals(ParseStatus.FAILED, pending.getParseStatus());
    }

    @Test
    void testProcessAsync_HallucinatedCompanyRemoved() throws Exception {
        UUID resumeId = UUID.randomUUID();
        UUID userId   = UUID.randomUUID();

        Resume source = new Resume();
        source.setParsedSkills("{\"skills\":[\"Java\"]}");
        source.setParsedExperience("[{\"company\":\"Real Co\"}]");

        Job job = new Job();
        job.setTitle("Dev");
        job.setDescription("Do stuff");
        job.setRequiredSkills(List.of("Java"));

        JobMatch match = new JobMatch();
        match.setMatchingSkills(List.of("Java"));
        match.setMissingSkills(List.of("Spring"));

        Resume pending = new Resume();
        pending.setId(resumeId);
        pending.setParseStatus(ParseStatus.PENDING);

        when(resumeRepository.findById(resumeId)).thenReturn(Optional.of(pending));
        when(openAIClient.tailorResume(anyList(), anyString(), anyString(), anyString(), anyList(), anyList(), anyList()))
                .thenReturn("{\"experience\":[{\"company\":\"Real Co\"},{\"company\":\"Fake Co\"}],\"unmatchedKeywords\":[]}");

        AtsRenderedDocument doc = new AtsRenderedDocument("pdf".getBytes(), "docx".getBytes());
        when(documentRenderer.render(any(ResumeJson.class), anyString())).thenReturn(doc);

        when(r2StorageClient.uploadGeneratedJson(any(), any(), any())).thenReturn("jsonKey");
        when(r2StorageClient.uploadGeneratedPdf(any(), any(), any())).thenReturn("pdfKey");
        when(r2StorageClient.uploadGeneratedDocx(any(), any(), any())).thenReturn("docxKey");

        resumeTailoringWorker.processAsync(resumeId, userId, source, job, match);

        verify(resumeRepository, times(2)).save(pending);
        assertEquals(ParseStatus.DONE, pending.getParseStatus());
        assertTrue(pending.getGeneratedContent().contains("Real Co"));
        assertFalse(pending.getGeneratedContent().contains("Fake Co"));
    }
}
