-- Seed 10 more sample jobs for the job market

INSERT INTO jobs (id, title, company, location, description, job_url, required_skills, source)
VALUES
    ('c1b48b99-3113-43ad-8d96-03c00c7f7bc1', 'Frontend Developer', 'TechNova', 'San Francisco, CA', 'We are looking for a Frontend Developer with experience in React, Next.js, and TailwindCSS. You will work on a high-traffic SaaS application.', 'https://technova.example.com/careers/frontend', '{"React","Next.js","TypeScript","TailwindCSS"}', 'seed'),
    ('c2b48b99-3113-43ad-8d96-03c00c7f7bc2', 'Data Scientist', 'Quantum Analytics', 'Remote', 'Join our data team to build predictive models and analyze complex datasets. Python and SQL required.', 'https://quantum.example.com/jobs/data', '{"Python","SQL","Machine Learning"}', 'seed'),
    ('c3b48b99-3113-43ad-8d96-03c00c7f7bc3', 'DevOps Engineer', 'CloudNative Inc.', 'Austin, TX', 'We need a DevOps Engineer experienced with AWS, Kubernetes, and CI/CD pipelines. You will be responsible for ensuring 99.99% uptime.', 'https://cloudnative.example.com/careers/devops', '{"AWS","Kubernetes","Docker"}', 'seed'),
    ('c4b48b99-3113-43ad-8d96-03c00c7f7bc4', 'UX/UI Designer', 'Creative Flow', 'New York, NY', 'Looking for a passionate UX/UI Designer to lead the redesign of our mobile app. Figma expertise is a must.', 'https://creativeflow.example.com/jobs/designer', '{"Figma","UI Design","UX Research"}', 'seed'),
    ('c5b48b99-3113-43ad-8d96-03c00c7f7bc5', 'Product Manager', 'Innovatech', 'Seattle, WA', 'As a Product Manager, you will work closely with engineering and design to deliver features that users love.', 'https://innovatech.example.com/careers/pm', '{"Product Strategy","Agile","Scrum"}', 'seed'),
    ('c6b48b99-3113-43ad-8d96-03c00c7f7bc6', 'Full Stack Engineer', 'Startup Hub', 'Remote', 'We are a fast-growing startup looking for a Full Stack Engineer (Node.js/React). You will have high ownership and impact.', 'https://startuphub.example.com/jobs/fullstack', '{"JavaScript","React","Node.js"}', 'seed'),
    ('c7b48b99-3113-43ad-8d96-03c00c7f7bc7', 'Mobile App Developer', 'Appify', 'Chicago, IL', 'Seeking a Mobile App Developer proficient in React Native or Flutter to build cross-platform applications.', 'https://appify.example.com/careers/mobile', '{"React Native","Flutter","iOS","Android"}', 'seed'),
    ('c8b48b99-3113-43ad-8d96-03c00c7f7bc8', 'Cybersecurity Analyst', 'SecureNet', 'Washington, D.C.', 'Join our security team to monitor, detect, and respond to security incidents. Experience with SIEM tools preferred.', 'https://securenet.example.com/jobs/security', '{"Cybersecurity","Network Security"}', 'seed'),
    ('c9b48b99-3113-43ad-8d96-03c00c7f7bc9', 'Marketing Specialist', 'Growth Co.', 'Los Angeles, CA', 'We are looking for a Marketing Specialist to manage our SEO, SEM, and social media channels.', 'https://growthco.example.com/careers/marketing', '{"SEO","SEM","Social Media"}', 'seed'),
    ('c0b48b99-3113-43ad-8d96-03c00c7f7bc0', 'Cloud Architect', 'Skyline Cloud', 'Boston, MA', 'The ideal candidate has deep expertise in Azure or AWS architecture and can guide clients through cloud migrations.', 'https://skyline.example.com/jobs/architect', '{"Cloud Architecture","Azure","AWS"}', 'seed')
ON CONFLICT (id) DO NOTHING;
